apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecowapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecowapi
  template:
    metadata:
      labels:
        app: wisecowapi
    spec:
      containers:
      - name: wisecow
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 4499
