pipeline {
    agent any
    environment {
        IMAGE_NAME = 'dpcode72/wisecow'
        IMAGE_TAG = '1.0'
        ANSIBLE_HOST_KEY_CHECKING = 'false'
    }
    tools {
        git 'Default'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'Gitlab', url: 'https://github.com/Deepak17460/Accuknox-DevOps_Trainee_Practical_Assessment-.git'
            }
        }
        stage('Docker-Build') {
            steps {
                dir('Wisecow') {
                    script {
                        docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                    }
                }
            }
        }
        stage('Docker-Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-login') {
                        docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push()
                    }
                }
            }
        }
        stage('Deploy-Helm-Chart') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG_FILE')]) {
                    dir('Ansible/javadeployment') {
                        sh """
                            # Change ownership to Jenkins user and set file permissions
                            chown jenkins:jenkins \$KUBECONFIG_FILE
                            chmod 600 \$KUBECONFIG_FILE
                            # Now export the KUBECONFIG environment variable
                            export KUBECONFIG=\$KUBECONFIG_FILE
                            # Run the helm upgrade command
                            helm upgrade --install javaapi . --namespace java-app \
                            --set image.repository=\${IMAGE_NAME},image.tag=\${IMAGE_TAG}
                        """
                    }
                }
            }
        }
    }
}
